services:
  license:
    image: "totvsengpro/license-dev"
    restart: unless-stopped
    networks:
      - protheus-net

  postgres-iniciado:
    image: "totvsengpro/postgres-dev:12.1.2210_bra"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - protheus-net

  dbaccess-postgres:
    image: "totvsengpro/dbaccess-postgres-dev"
    restart: unless-stopped
    depends_on:
      - postgres-iniciado
      - license
    volumes:
      - ./resources/dbaccess.ini:/opt/totvs/dbaccess/multi/dbaccess.ini
    networks:
      - protheus-net

  appserver:
    image: "totvsengpro/appserver-dev"
    restart: unless-stopped
    depends_on:
      - dbaccess-postgres
      - license
    volumes:
      - ./resources/appserver.ini:/opt/totvs/appserver/appserver.ini
      - ./resources/TTTM120.RPO:/opt/totvs/protheus/apo/tttm120.rpo
      - ./resources/sx2.unq:/opt/totvs/protheus/protheus_data/systemload/sx2.unq
      - ./resources/sxsbra.txt:/opt/totvs/protheus/protheus_data/systemload/sxsbra.txt
      - protheus-data:/opt/totvs/protheus/protheus_data
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8081:8081"
    networks:
      - protheus-net

volumes:
  postgres-data:
  protheus-data:

networks:
  protheus-net:
    driver: bridge
